/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jhu.cvrg.portal.resourcerequest.service.base;

import com.jhu.cvrg.portal.resourcerequest.model.ResourceRequest;
import com.jhu.cvrg.portal.resourcerequest.service.ResourceRequestLocalService;
import com.jhu.cvrg.portal.resourcerequest.service.TransactionLocalService;
import com.jhu.cvrg.portal.resourcerequest.service.persistence.ResourceRequestPersistence;
import com.jhu.cvrg.portal.resourcerequest.service.persistence.TransactionPersistence;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.annotation.BeanReference;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the resource request local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.jhu.cvrg.portal.resourcerequest.service.impl.ResourceRequestLocalServiceImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. Always use {@link com.jhu.cvrg.portal.resourcerequest.service.ResourceRequestLocalServiceUtil} to access the resource request local service.
 * </p>
 *
 * @author Chris Jurado
 * @see com.jhu.cvrg.portal.resourcerequest.service.impl.ResourceRequestLocalServiceImpl
 * @see com.jhu.cvrg.portal.resourcerequest.service.ResourceRequestLocalServiceUtil
 * @generated
 */
public abstract class ResourceRequestLocalServiceBaseImpl
	implements ResourceRequestLocalService {
	/**
	 * Adds the resource request to the database. Also notifies the appropriate model listeners.
	 *
	 * @param resourceRequest the resource request to add
	 * @return the resource request that was added
	 * @throws SystemException if a system exception occurred
	 */
	public ResourceRequest addResourceRequest(ResourceRequest resourceRequest)
		throws SystemException {
		resourceRequest.setNew(true);

		return resourceRequestPersistence.update(resourceRequest, false);
	}

	/**
	 * Creates a new resource request with the primary key. Does not add the resource request to the database.
	 *
	 * @param requestId the primary key for the new resource request
	 * @return the new resource request
	 */
	public ResourceRequest createResourceRequest(long requestId) {
		return resourceRequestPersistence.create(requestId);
	}

	/**
	 * Deletes the resource request with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param requestId the primary key of the resource request to delete
	 * @throws PortalException if a resource request with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteResourceRequest(long requestId)
		throws PortalException, SystemException {
		resourceRequestPersistence.remove(requestId);
	}

	/**
	 * Deletes the resource request from the database. Also notifies the appropriate model listeners.
	 *
	 * @param resourceRequest the resource request to delete
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteResourceRequest(ResourceRequest resourceRequest)
		throws SystemException {
		resourceRequestPersistence.remove(resourceRequest);
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return resourceRequestPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return resourceRequestPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @param orderByComparator the comparator to order the results by
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return resourceRequestPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Counts the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return resourceRequestPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Gets the resource request with the primary key.
	 *
	 * @param requestId the primary key of the resource request to get
	 * @return the resource request
	 * @throws PortalException if a resource request with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public ResourceRequest getResourceRequest(long requestId)
		throws PortalException, SystemException {
		return resourceRequestPersistence.findByPrimaryKey(requestId);
	}

	/**
	 * Gets a range of all the resource requests.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of resource requests to return
	 * @param end the upper bound of the range of resource requests to return (not inclusive)
	 * @return the range of resource requests
	 * @throws SystemException if a system exception occurred
	 */
	public List<ResourceRequest> getResourceRequests(int start, int end)
		throws SystemException {
		return resourceRequestPersistence.findAll(start, end);
	}

	/**
	 * Gets the number of resource requests.
	 *
	 * @return the number of resource requests
	 * @throws SystemException if a system exception occurred
	 */
	public int getResourceRequestsCount() throws SystemException {
		return resourceRequestPersistence.countAll();
	}

	/**
	 * Updates the resource request in the database. Also notifies the appropriate model listeners.
	 *
	 * @param resourceRequest the resource request to update
	 * @return the resource request that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public ResourceRequest updateResourceRequest(
		ResourceRequest resourceRequest) throws SystemException {
		resourceRequest.setNew(false);

		return resourceRequestPersistence.update(resourceRequest, true);
	}

	/**
	 * Updates the resource request in the database. Also notifies the appropriate model listeners.
	 *
	 * @param resourceRequest the resource request to update
	 * @param merge whether to merge the resource request with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the resource request that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public ResourceRequest updateResourceRequest(
		ResourceRequest resourceRequest, boolean merge)
		throws SystemException {
		resourceRequest.setNew(false);

		return resourceRequestPersistence.update(resourceRequest, merge);
	}

	/**
	 * Gets the resource request local service.
	 *
	 * @return the resource request local service
	 */
	public ResourceRequestLocalService getResourceRequestLocalService() {
		return resourceRequestLocalService;
	}

	/**
	 * Sets the resource request local service.
	 *
	 * @param resourceRequestLocalService the resource request local service
	 */
	public void setResourceRequestLocalService(
		ResourceRequestLocalService resourceRequestLocalService) {
		this.resourceRequestLocalService = resourceRequestLocalService;
	}

	/**
	 * Gets the resource request persistence.
	 *
	 * @return the resource request persistence
	 */
	public ResourceRequestPersistence getResourceRequestPersistence() {
		return resourceRequestPersistence;
	}

	/**
	 * Sets the resource request persistence.
	 *
	 * @param resourceRequestPersistence the resource request persistence
	 */
	public void setResourceRequestPersistence(
		ResourceRequestPersistence resourceRequestPersistence) {
		this.resourceRequestPersistence = resourceRequestPersistence;
	}

	/**
	 * Gets the transaction local service.
	 *
	 * @return the transaction local service
	 */
	public TransactionLocalService getTransactionLocalService() {
		return transactionLocalService;
	}

	/**
	 * Sets the transaction local service.
	 *
	 * @param transactionLocalService the transaction local service
	 */
	public void setTransactionLocalService(
		TransactionLocalService transactionLocalService) {
		this.transactionLocalService = transactionLocalService;
	}

	/**
	 * Gets the transaction persistence.
	 *
	 * @return the transaction persistence
	 */
	public TransactionPersistence getTransactionPersistence() {
		return transactionPersistence;
	}

	/**
	 * Sets the transaction persistence.
	 *
	 * @param transactionPersistence the transaction persistence
	 */
	public void setTransactionPersistence(
		TransactionPersistence transactionPersistence) {
		this.transactionPersistence = transactionPersistence;
	}

	/**
	 * Gets the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Gets the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Gets the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Gets the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Gets the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Gets the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Gets the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query to perform
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = resourceRequestPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = ResourceRequestLocalService.class)
	protected ResourceRequestLocalService resourceRequestLocalService;
	@BeanReference(type = ResourceRequestPersistence.class)
	protected ResourceRequestPersistence resourceRequestPersistence;
	@BeanReference(type = TransactionLocalService.class)
	protected TransactionLocalService transactionLocalService;
	@BeanReference(type = TransactionPersistence.class)
	protected TransactionPersistence transactionPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}