/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edu.jhu.cvrg.portal.resourcerequest.model.impl;

import com.jhu.cvrg.portal.resourcerequest.model.edu;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import edu.jhu.cvrg.portal.resourcerequest.model.Transaction;
import edu.jhu.cvrg.portal.resourcerequest.model.TransactionModel;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the Transaction service. Represents a row in the &quot;JHU_resource_request_Transaction&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link edu.jhu.cvrg.portal.resourcerequest.model.TransactionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TransactionImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a transaction model instance should use the {@link edu.jhu.cvrg.portal.resourcerequest.model.Transaction} interface instead.
 * </p>
 *
 * @author Chris Jurado
 * @see TransactionImpl
 * @see edu.jhu.cvrg.portal.resourcerequest.model.Transaction
 * @see edu.jhu.cvrg.portal.resourcerequest.model.TransactionModel
 * @generated
 */
public class TransactionModelImpl extends BaseModelImpl<Transaction>
	implements TransactionModel {
	public static final String TABLE_NAME = "JHU_resource_request_Transaction";
	public static final Object[][] TABLE_COLUMNS = {
			{ "transactionId", new Integer(Types.BIGINT) },
			{ "date_", new Integer(Types.TIMESTAMP) },
			{ "memberId", new Integer(Types.BIGINT) },
			{ "action", new Integer(Types.VARCHAR) },
			{ "studyId", new Integer(Types.BIGINT) },
			{ "approverId", new Integer(Types.BIGINT) },
			{ "comment_", new Integer(Types.VARCHAR) },
			{ "ip", new Integer(Types.VARCHAR) }
		};
	public static final String TABLE_SQL_CREATE = "create table JHU_resource_request_Transaction (transactionId LONG not null primary key,date_ DATE null,memberId LONG,action VARCHAR(75) null,studyId LONG,approverId LONG,comment_ VARCHAR(250) null,ip VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table JHU_resource_request_Transaction";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.jhu.cvrg.portal.resourcerequest.model.Transaction"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.jhu.cvrg.portal.resourcerequest.model.Transaction"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.jhu.cvrg.portal.resourcerequest.model.Transaction"));

	public TransactionModelImpl() {
	}

	public long getPrimaryKey() {
		return _transactionId;
	}

	public void setPrimaryKey(long pk) {
		setTransactionId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_transactionId);
	}

	public long getTransactionId() {
		return _transactionId;
	}

	public void setTransactionId(long transactionId) {
		_transactionId = transactionId;
	}

	public Date getDate() {
		return _date;
	}

	public void setDate(Date date) {
		_date = date;
	}

	public long getMemberId() {
		return _memberId;
	}

	public void setMemberId(long memberId) {
		_memberId = memberId;
	}

	public String getAction() {
		if (_action == null) {
			return StringPool.BLANK;
		}
		else {
			return _action;
		}
	}

	public void setAction(String action) {
		_action = action;
	}

	public long getStudyId() {
		return _studyId;
	}

	public void setStudyId(long studyId) {
		_studyId = studyId;
	}

	public long getApproverId() {
		return _approverId;
	}

	public void setApproverId(long approverId) {
		_approverId = approverId;
	}

	public String getComment() {
		if (_comment == null) {
			return StringPool.BLANK;
		}
		else {
			return _comment;
		}
	}

	public void setComment(String comment) {
		_comment = comment;
	}

	public String getIp() {
		if (_ip == null) {
			return StringPool.BLANK;
		}
		else {
			return _ip;
		}
	}

	public void setIp(String ip) {
		_ip = ip;
	}

	public Transaction toEscapedModel() {
		if (isEscapedModel()) {
			return (Transaction)this;
		}
		else {
			return (Transaction)Proxy.newProxyInstance(Transaction.class.getClassLoader(),
				new Class[] { Transaction.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					Transaction.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		TransactionImpl transactionImpl = new TransactionImpl();

		transactionImpl.setTransactionId(getTransactionId());

		transactionImpl.setDate(getDate());

		transactionImpl.setMemberId(getMemberId());

		transactionImpl.setAction(getAction());

		transactionImpl.setStudyId(getStudyId());

		transactionImpl.setApproverId(getApproverId());

		transactionImpl.setComment(getComment());

		transactionImpl.setIp(getIp());

		return transactionImpl;
	}

	public int compareTo(Transaction transaction) {
		long pk = transaction.getPrimaryKey();

		if (getPrimaryKey() < pk) {
			return -1;
		}
		else if (getPrimaryKey() > pk) {
			return 1;
		}
		else {
			return 0;
		}
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Transaction transaction = null;

		try {
			transaction = (Transaction)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = transaction.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{transactionId=");
		sb.append(getTransactionId());
		sb.append(", date=");
		sb.append(getDate());
		sb.append(", memberId=");
		sb.append(getMemberId());
		sb.append(", action=");
		sb.append(getAction());
		sb.append(", studyId=");
		sb.append(getStudyId());
		sb.append(", approverId=");
		sb.append(getApproverId());
		sb.append(", comment=");
		sb.append(getComment());
		sb.append(", ip=");
		sb.append(getIp());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("edu.jhu.cvrg.portal.resourcerequest.model.Transaction");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>transactionId</column-name><column-value><![CDATA[");
		sb.append(getTransactionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>date</column-name><column-value><![CDATA[");
		sb.append(getDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>memberId</column-name><column-value><![CDATA[");
		sb.append(getMemberId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>action</column-name><column-value><![CDATA[");
		sb.append(getAction());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>studyId</column-name><column-value><![CDATA[");
		sb.append(getStudyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>approverId</column-name><column-value><![CDATA[");
		sb.append(getApproverId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>comment</column-name><column-value><![CDATA[");
		sb.append(getComment());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ip</column-name><column-value><![CDATA[");
		sb.append(getIp());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _transactionId;
	private Date _date;
	private long _memberId;
	private String _action;
	private long _studyId;
	private long _approverId;
	private String _comment;
	private String _ip;
	private transient ExpandoBridge _expandoBridge;
}