/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jhu.cvrg.portal.resourcerequest.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ResourceRequest service. Represents a row in the &quot;JHU_resource_request_ResourceRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.jhu.cvrg.portal.resourcerequest.model.impl.ResourceRequestModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.jhu.cvrg.portal.resourcerequest.model.impl.ResourceRequestImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a resource request model instance should use the {@link ResourceRequest} interface instead.
 * </p>
 *
 * @author Chris Jurado
 * @see ResourceRequest
 * @see com.jhu.cvrg.portal.resourcerequest.model.impl.ResourceRequestImpl
 * @see com.jhu.cvrg.portal.resourcerequest.model.impl.ResourceRequestModelImpl
 * @generated
 */
public interface ResourceRequestModel extends BaseModel<ResourceRequest> {
	/**
	 * Gets the primary key of this resource request.
	 *
	 * @return the primary key of this resource request
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this resource request
	 *
	 * @param pk the primary key of this resource request
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the request id of this resource request.
	 *
	 * @return the request id of this resource request
	 */
	public long getRequestId();

	/**
	 * Sets the request id of this resource request.
	 *
	 * @param requestId the request id of this resource request
	 */
	public void setRequestId(long requestId);

	/**
	 * Gets the requester id of this resource request.
	 *
	 * @return the requester id of this resource request
	 */
	public long getRequesterId();

	/**
	 * Sets the requester id of this resource request.
	 *
	 * @param requesterId the requester id of this resource request
	 */
	public void setRequesterId(long requesterId);

	/**
	 * Gets the approver id of this resource request.
	 *
	 * @return the approver id of this resource request
	 */
	public long getApproverId();

	/**
	 * Sets the approver id of this resource request.
	 *
	 * @param approverId the approver id of this resource request
	 */
	public void setApproverId(long approverId);

	/**
	 * Gets the approved of this resource request.
	 *
	 * @return the approved of this resource request
	 */
	public boolean getApproved();

	/**
	 * Determines if this resource request is approved.
	 *
	 * @return <code>true</code> if this resource request is approved; <code>false</code> otherwise
	 */
	public boolean isApproved();

	/**
	 * Sets whether this {$entity.humanName} is approved.
	 *
	 * @param approved the approved of this resource request
	 */
	public void setApproved(boolean approved);

	/**
	 * Gets the declined of this resource request.
	 *
	 * @return the declined of this resource request
	 */
	public boolean getDeclined();

	/**
	 * Determines if this resource request is declined.
	 *
	 * @return <code>true</code> if this resource request is declined; <code>false</code> otherwise
	 */
	public boolean isDeclined();

	/**
	 * Sets whether this {$entity.humanName} is declined.
	 *
	 * @param declined the declined of this resource request
	 */
	public void setDeclined(boolean declined);

	/**
	 * Gets the study id of this resource request.
	 *
	 * @return the study id of this resource request
	 */
	public long getStudyId();

	/**
	 * Sets the study id of this resource request.
	 *
	 * @param studyId the study id of this resource request
	 */
	public void setStudyId(long studyId);

	/**
	 * Gets the message of this resource request.
	 *
	 * @return the message of this resource request
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this resource request.
	 *
	 * @param message the message of this resource request
	 */
	public void setMessage(String message);

	/**
	 * Gets the date sent of this resource request.
	 *
	 * @return the date sent of this resource request
	 */
	public Date getDateSent();

	/**
	 * Sets the date sent of this resource request.
	 *
	 * @param dateSent the date sent of this resource request
	 */
	public void setDateSent(Date dateSent);

	/**
	 * Gets the date handled of this resource request.
	 *
	 * @return the date handled of this resource request
	 */
	@AutoEscape
	public String getDateHandled();

	/**
	 * Sets the date handled of this resource request.
	 *
	 * @param dateHandled the date handled of this resource request
	 */
	public void setDateHandled(String dateHandled);

	/**
	 * Gets the group id of this resource request.
	 *
	 * @return the group id of this resource request
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this resource request.
	 *
	 * @param groupId the group id of this resource request
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the company id of this resource request.
	 *
	 * @return the company id of this resource request
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this resource request.
	 *
	 * @param companyId the company id of this resource request
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets a copy of this resource request as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public ResourceRequest toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ResourceRequest resourceRequest);

	public int hashCode();

	public String toString();

	public String toXmlString();
}