/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edu.jhu.cvrg.portal.resourcerequest.model;

import com.jhu.cvrg.portal.resourcerequest.model.Request;
import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Request service. Represents a row in the &quot;JHU_Request&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link edu.jhu.cvrg.portal.resourcerequest.model.impl.RequestModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link edu.jhu.cvrg.portal.resourcerequest.model.impl.RequestImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a request model instance should use the {@link Request} interface instead.
 * </p>
 *
 * @author Chris Jurado
 * @see Request
 * @see edu.jhu.cvrg.portal.resourcerequest.model.impl.RequestImpl
 * @see edu.jhu.cvrg.portal.resourcerequest.model.impl.RequestModelImpl
 * @generated
 */
public interface RequestModel extends BaseModel<Request> {
	/**
	 * Gets the primary key of this request.
	 *
	 * @return the primary key of this request
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this request
	 *
	 * @param pk the primary key of this request
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the request id of this request.
	 *
	 * @return the request id of this request
	 */
	public long getRequestId();

	/**
	 * Sets the request id of this request.
	 *
	 * @param requestId the request id of this request
	 */
	public void setRequestId(long requestId);

	/**
	 * Gets the requester id of this request.
	 *
	 * @return the requester id of this request
	 */
	public long getRequesterId();

	/**
	 * Sets the requester id of this request.
	 *
	 * @param requesterId the requester id of this request
	 */
	public void setRequesterId(long requesterId);

	/**
	 * Gets the approver id of this request.
	 *
	 * @return the approver id of this request
	 */
	public long getApproverId();

	/**
	 * Sets the approver id of this request.
	 *
	 * @param approverId the approver id of this request
	 */
	public void setApproverId(long approverId);

	/**
	 * Gets the approved of this request.
	 *
	 * @return the approved of this request
	 */
	public boolean getApproved();

	/**
	 * Determines if this request is approved.
	 *
	 * @return <code>true</code> if this request is approved; <code>false</code> otherwise
	 */
	public boolean isApproved();

	/**
	 * Sets whether this {$entity.humanName} is approved.
	 *
	 * @param approved the approved of this request
	 */
	public void setApproved(boolean approved);

	/**
	 * Gets the declined of this request.
	 *
	 * @return the declined of this request
	 */
	public boolean getDeclined();

	/**
	 * Determines if this request is declined.
	 *
	 * @return <code>true</code> if this request is declined; <code>false</code> otherwise
	 */
	public boolean isDeclined();

	/**
	 * Sets whether this {$entity.humanName} is declined.
	 *
	 * @param declined the declined of this request
	 */
	public void setDeclined(boolean declined);

	/**
	 * Gets the study id of this request.
	 *
	 * @return the study id of this request
	 */
	public long getStudyId();

	/**
	 * Sets the study id of this request.
	 *
	 * @param studyId the study id of this request
	 */
	public void setStudyId(long studyId);

	/**
	 * Gets the message of this request.
	 *
	 * @return the message of this request
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this request.
	 *
	 * @param message the message of this request
	 */
	public void setMessage(String message);

	/**
	 * Gets the date sent of this request.
	 *
	 * @return the date sent of this request
	 */
	@AutoEscape
	public String getDateSent();

	/**
	 * Sets the date sent of this request.
	 *
	 * @param dateSent the date sent of this request
	 */
	public void setDateSent(String dateSent);

	/**
	 * Gets the date handled of this request.
	 *
	 * @return the date handled of this request
	 */
	@AutoEscape
	public String getDateHandled();

	/**
	 * Sets the date handled of this request.
	 *
	 * @param dateHandled the date handled of this request
	 */
	public void setDateHandled(String dateHandled);

	/**
	 * Gets the group id of this request.
	 *
	 * @return the group id of this request
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this request.
	 *
	 * @param groupId the group id of this request
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the company id of this request.
	 *
	 * @return the company id of this request
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this request.
	 *
	 * @param companyId the company id of this request
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets a copy of this request as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public Request toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Request request);

	public int hashCode();

	public String toString();

	public String toXmlString();
}